--- 
abstract: Run a callback after a file has been compiled
author: Robert 'phaylon' Sedlacek <rs@474.at>
build_requires: 
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Filter-EOF
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Carp: 0
  Filter::Util::Call: 1.0601
version: 0.03
